# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path("vendor/starcorp/lemp", File.dirname(__FILE__))

serverJsonPath = File.expand_path("Server.json", File.dirname(__FILE__))

require File.expand_path(confDir + '/scripts/lemp.rb')

Vagrant.require_version '>= 1.9.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    if File.exist? serverJsonPath then
        settings = JSON::parse(File.read(serverJsonPath))
    else
        abort "Server settings file not found in #{confDir}"
    end

    Lemp.configure(config, settings)

    if defined? VagrantPlugins::HostsUpdater
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    end
end
